### ISSUE TITLE
Unable to install on Mojave 10.14.2

### ISSUE THREAD

**Issue by Mayeu** [apjanke/homebrew-ronn-ng#1]
Hello 👋 

I am unable to install ronn-ng on Mojave.

It seems that there is some error when the C compiler is checked:
```
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
```

Here is the full logs:
<details>
```
2019-01-31 12:36:31 +0100

gem
install
/Users/m/Library/Caches/Homebrew/downloads/9cf2d7c9477d37fe91f96a26ab814ff83e779eaa9a8ea1f672eaedd83d8c5116--nokogiri-1.9.0.gem
--no-document
--ignore-dependencies
--install-dir
/usr/local/Cellar/ronn-ng/0.8.0/libexec

Building native extensions. This could take a while...
ERROR:  Error installing /Users/m/Library/Caches/Homebrew/downloads/9cf2d7c9477d37fe91f96a26ab814ff83e779eaa9a8ea1f672eaedd83d8c5116--nokogiri-1.9.0.gem:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/nokogiri-1.9.0/ext/nokogiri
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0 -r ./siteconf20190131-19364-1lrj01y.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.6.0_1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'mini_portile2' (~> 2.4.0) among 8 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/private/tmp/ronn-ng-20190131-19340-m1kaoc/ronn-ng-0.8.0/.brew_home/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/gems/2.6.0:/usr/local/Cellar/ronn-ng/0.8.0/libexec', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from extconf.rb:465:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Cellar/ronn-ng/0.8.0/libexec/extensions/x86_64-darwin-18/2.6.0/nokogiri-1.9.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/nokogiri-1.9.0 for inspection.
Results logged to /usr/local/Cellar/ronn-ng/0.8.0/libexec/extensions/x86_64-darwin-18/2.6.0/nokogiri-1.9.0/gem_make.out

HOMEBREW_VERSION: 1.9.3-77-g2062c51
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2062c5191da477131973726b0f7c82c99fe169c4
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2255adf79fc504584aa045f246ed58edf8c46de3
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/m/Library/Caches/Homebrew
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/ruby:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/libyaml/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/ruby/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/openssl/bin:/usr/local/opt/ruby/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
</details>

**Comment by Mayeu** [comment]
BTW: I was installing via your Homebrew tap 👍

**Comment by apjanke** [comment]
That's a little surprising. I'm unable to reproduce. Maybe you haven't accepted the Xcode SDK or installed the Command Line Tools on your machine?

Do you have any alternate C compilers installed?

**Comment by Mayeu** [comment]
Thank you for your answer. I don't have a Mojave machine anymore, and I can't reproduce on Catalina. So let's close this.
